# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

admin:
    resource: "@IcanBundle/Resources/config/routing.yml"
    prefix:   /admin

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

auntenticarUsuario:
    path:  /usuario/autenticar
    defaults: { _controller: IcanBundle:Usuario:autenticar, _format: json }
    
forgetPass:
    path:  /usuario/olvidoContrasenna
    defaults: { _controller: IcanBundle:Usuario:olvidoContrasenna, _format: json }
    
login:
    path:  /login 
    defaults: { _controller: IcanBundle:Usuario:login }
  
login_check:
    path: /check
    
logout:
    path: /logout  

denegado:
    path:  /denegado
    defaults: { _controller: IcanBundle:Usuario:denegado }
