IcanBundle\Entity\SeccionProducto:
  type: entity
  repositoryClass: IcanBundle\Entity\SeccionProductoRepository
  table: seccion_producto
  id:
    seccionProductoId:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      column: producto_id
      generator:
        strategy: AUTO
  fields:
    nombre:
      type: string
      length: 255
      options:
        fixed: false
      nullable: false
    titulo:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    descripcion:
      type: text
      nullable: false
    tags:
      type: text
      nullable: false
    imagen:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    stock:
      type: integer
      options:
        unsigned: false
      nullable: false
    precio:
      type: integer
      options:
        unsigned: false
      nullable: false
    precioOferta:
      type: integer
      options:
        unsigned: false
      nullable: false
      column: precio_oferta
    mostrarPrecio:
      type: boolean
      nullable: false
      column: mostrar_precio
    estado:
      type: boolean
      nullable: true
    fechapublicacion:
      type: datetime
      nullable: true
    url:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    views:
      type: integer
      options:
        unsigned: false
      nullable: false
  manyToOne:
    producto:
      targetEntity: Producto
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        producto_id:
          referencedColumnName: producto_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
