IcanBundle\Entity\SeoOnPage:
    type: entity
    repositoryClass: IcanBundle\Entity\SeoOnPageRepository
    table: seo_on_page
    id:
        paginaId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: pagina_id
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 160
            options:
                fixed: false
        tags:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        url:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
