IcanBundle\Entity\Slider:
  type: entity
  repositoryClass: IcanBundle\Entity\SliderRepository
  table: slider
  id:
    sliderId:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      column: slider_id
      generator:
        strategy: AUTO
  fields:
    nombre:
      type: string
      length: 255
      options:
        fixed: false
      nullable: false
    titulo:
      type: string
      length: 255
      options:
        fixed: false
      nullable: false
    descripcion:
      type: text
      nullable: false
    estado:
      type: boolean
      nullable: true
    imagen:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    url:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    formadeabrir:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    cantclick:
      type: integer
      options:
        unsigned: false
      nullable: true
    posicion:
      type: integer
      options:
        unsigned: false
      nullable: true
    fechapublicacion:
      type: datetime
      nullable: true
  lifecycleCallbacks: {  }
