IcanBundle\Entity\TipoProducto:
  type: entity
  repositoryClass: IcanBundle\Entity\TipoProductoRepository
  table: tipo_producto
  id:
    tipoProductoId:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      column: tipo_producto_id
      generator:
        strategy: AUTO
  fields:
    tipoProducto:
      type: string
      length: 255
      options:
        fixed: false
      nullable: false
  lifecycleCallbacks: {  }
