IcanBundle\Entity\Video:
  type: entity
  repositoryClass: IcanBundle\Entity\VideoRepository
  table: video
  id:
    videoId:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      column: video_id
      generator:
        strategy: AUTO
  fields:
    nombre:
      type: string
      length: 255
      options:
        fixed: false
      nullable: false
    descripcion:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    estado:
      type: boolean
      nullable: true
    imagen:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
    url:
      type: string
      length: 255
      options:
        fixed: false
      nullable: true
  lifecycleCallbacks: {  }
